#!/bin/bash

# Extract metadata from mkv files recursively and generate a web page


videos_directory="$1"
page_title="$2"
target="generated"
index="$target"/index.html

check_dependency() {
  if [ -z `which $1` ]; then
    echo "Missing dependency: $1" && exit 1
  fi
}

extract_metadata_and_generate_page() {
  movie="$1"
  name=$(basename "$movie")
  title=$(mediainfo "$movie" 2> /dev/null | grep "Movie name" | awk -F ": " '{print $2}')

  if [ -z "$title" ]; then
    echo "No title found for $name"
    title="$name"
  fi

  nbcovers=`mkvmerge -i "$movie" | grep "type 'image" | wc -l`
  if [ "$nbcovers" -eq 0 ]; then
    echo "No cover found for $name"
    cover=""
  else
    cover="covers/cover_"$title".jpg"
    cover_id=`mkvmerge -i "$movie" | grep "type 'image" | head -n 1 | awk '{print $3}'`
    mkvextract attachments "$movie" "$cover_id$target"/"$cover" > /dev/null 2>&1
  fi

  languages=`mkvmerge -i -F json "$movie" | jq -r '.tracks[] | select(.type=="audio") | .properties.language'`
  while read -r lang; do
    li="      <li class=\"selected\" onclick=\"filterByLang(this)\">$lang</li>"
    if [ -z "`grep "$li" "$index".start`" ]; then
      echo "$li" >> "$index".start
    fi
  done <<< "$languages"

  languages="${languages//[$'\n']/ }"
  title="$title [$languages]"
  echo "      <img class=\"$languages\" src=\"$cover\" title=\"$title\" alt=\"[${title}]\" />" >> "$index".part1
}

generate() {
  echo "Gathering metadata..."
  shopt -s globstar
  for movie in "$videos_directory"/**/*; do
    if [ ! -d "$movie" ]; then
      ext="${movie##*.}"
      if [ "$ext" != "mkv" ]; then
        echo "Cannot get metadata (is not mkv) from $movie"
      else
        extract_metadata_and_generate_page "$movie"
      fi
    fi
  done
}

if [ "$#" -ne 2 ]; then
  echo "Usage: ./mkvisu VIDEOS_ROOT_DIR TITLE" && exit 1
fi

if [ ! -d "$videos_directory" ]; then
  echo "$videos_directory not found!" && exit 1
fi

check_dependency "mkvmerge"
check_dependency "mkvextract"
check_dependency "mediainfo"
check_dependency "jq"

mkdir -p "$target"/covers
cp templates/* "$target"
generate
cat "$index".start "$index".part1 "$index".end > "$index"
sed -i "s/TITLE/$page_title/g" "$index"
rm "$index".*
